/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Com.example.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Sushil Shrestha
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_sellproduct = new javax.swing.JMenu();
        jMenuItem_AddProduct = new javax.swing.JMenuItem();
        jMenuItem_sellproduct = new javax.swing.JMenuItem();
        jMenu_login = new javax.swing.JMenuItem();
        jMenuItem_logout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        jMenu_sellproduct.setText("Application");

        jMenuItem_AddProduct.setText("AddProduct");
        jMenuItem_AddProduct.setEnabled(false);
        jMenuItem_AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddProductActionPerformed(evt);
            }
        });
        jMenu_sellproduct.add(jMenuItem_AddProduct);

        jMenuItem_sellproduct.setText("Sell Product");
        jMenuItem_sellproduct.setEnabled(false);
        jMenuItem_sellproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_sellproductActionPerformed(evt);
            }
        });
        jMenu_sellproduct.add(jMenuItem_sellproduct);

        jMenu_login.setText("Login");
        jMenu_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_loginActionPerformed(evt);
            }
        });
        jMenu_sellproduct.add(jMenu_login);

        jMenuItem_logout.setText("Logout");
        jMenuItem_logout.setEnabled(false);
        jMenuItem_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_logoutActionPerformed(evt);
            }
        });
        jMenu_sellproduct.add(jMenuItem_logout);

        jMenuBar1.add(jMenu_sellproduct);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddProductActionPerformed
        // TODO add your handling code here:
        AddProduct ob=new AddProduct();
        desktop.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AddProductActionPerformed

    private void jMenu_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_loginActionPerformed
        // TODO add your handling code here:
        LoginUser ob=new LoginUser();
        desktop.add(ob);
        ob.setVisible(true);
   
    }//GEN-LAST:event_jMenu_loginActionPerformed

    private void jMenuItem_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_logoutActionPerformed
        // TODO add your handling code here:
        MainFrame.jMenuItem_AddProduct.setEnabled(false);
            MainFrame.jMenuItem_sellproduct.setEnabled(false);
            MainFrame.jMenuItem_logout.setEnabled(false);
            MainFrame.jMenu_login.setEnabled(true);
            JOptionPane.showMessageDialog(null,"Logged out successful");
    }//GEN-LAST:event_jMenuItem_logoutActionPerformed

    private void jMenuItem_sellproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_sellproductActionPerformed
        // TODO add your handling code here:
        SellProduct obj=new SellProduct();
        desktop.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem_sellproductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem_AddProduct;
    public static javax.swing.JMenuItem jMenuItem_logout;
    public static javax.swing.JMenuItem jMenuItem_sellproduct;
    public static javax.swing.JMenuItem jMenu_login;
    private javax.swing.JMenu jMenu_sellproduct;
    // End of variables declaration//GEN-END:variables
}
