/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Com.example.view;

import Com.example.common.TrackUser;
import Com.example.controller.ProductDAO;
import Com.example.controller.SalesDAO;
import Com.example.model.Product;
import Com.example.model.Sales;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sushil Shrestha
 */
public class SellProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form SellProduct
     * 
     */
    DefaultTableModel model;
    
    public SellProduct() {
        initComponents();
        model=new DefaultTableModel(null,new Object[]{"pid","name","price","qty","total"});
        jTable_sellproduct.setModel(model);
        Date today=new Date();
        jLabel_date.setText(today.toString());
        jLabel_username.setText("Logged in as "+TrackUser.uname);
    }

    private void computeGrandTotal(){
        int rowCount=jTable_sellproduct.getRowCount();
        double gTotal=0;
        for(int i=0;i<rowCount;i++){
            double total=Double.parseDouble(jTable_sellproduct.getValueAt(i,4).toString());
            gTotal+=total;
        }
        jLabel_grandtotal.setText(gTotal+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_date = new javax.swing.JLabel();
        jLabel_productid = new javax.swing.JLabel();
        jTextField_productid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_sellproduct = new javax.swing.JTable();
        jLabel_username = new javax.swing.JLabel();
        jLabel_grandtotal1 = new javax.swing.JLabel();
        jLabel_grandtotal = new javax.swing.JLabel();
        jButton_print = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();

        setClosable(true);

        jLabel_date.setText("Date");

        jLabel_productid.setText("product id");

        jTextField_productid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_productidActionPerformed(evt);
            }
        });

        jTable_sellproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_sellproduct);

        jLabel_username.setText("Username");

        jLabel_grandtotal1.setText("Grand Total");

        jLabel_grandtotal.setText("jLabel5");

        jButton_print.setText("print");
        jButton_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_printActionPerformed(evt);
            }
        });

        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_print))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_grandtotal1)
                .addGap(57, 57, 57)
                .addComponent(jLabel_grandtotal)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_productid)
                .addGap(67, 67, 67)
                .addComponent(jTextField_productid, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_remove)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_date)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_productid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_productid)
                    .addComponent(jButton_remove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_grandtotal1)
                            .addComponent(jLabel_grandtotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_print))
                    .addComponent(jLabel_username))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_productidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_productidActionPerformed
        // TODO add your handling code here:
        String id=jTextField_productid.getText();
        if(!id.equals("")){
            int pid=Integer.parseInt(id);
            ProductDAO pDAO=new ProductDAO();
            ArrayList<Product> list=pDAO.fetchDataWithId(pid);
            if(list.size()>0){
                model.addRow(new Object[]{list.get(0).getId(),list.get(0).getName(),list.get(0).getPrice(),"1",list.get(0).getPrice()});
                computeGrandTotal();
            }
        }
    }//GEN-LAST:event_jTextField_productidActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        // TODO add your handling code here:
        int row=jTable_sellproduct.getSelectedRow();
        model.removeRow(row);
        computeGrandTotal();
    }//GEN-LAST:event_jButton_removeActionPerformed
    public void printBill(){
        String str="Namaste Super Market\nSinamangal,Kathmandu\n\n\n";
        
        int rowCount=jTable_sellproduct.getRowCount();
        for(int i=0;i<rowCount;i++){
            str+=model.getValueAt(i, 0)+" ";
            str+=model.getValueAt(i, 1)+" ";
            str+=model.getValueAt(i, 2)+" ";
            str+=model.getValueAt(i, 3)+" ";
            str+=model.getValueAt(i, 4)+"\n";
        }
        str+="Grand Total: "+jLabel_grandtotal.getText();
        str+="\nThank You for visiting us!!!!!!!!!!!!";
        
        BillPrint ob=new BillPrint();
        ob.jTextArea_Bill.setLineWrap(true);
        ob.jTextArea_Bill.setText(str);
        try{
            ob.jTextArea_Bill.print();
            
        }catch(Exception ex){
            System.out.println(ex);
        }
        
           
        
    }
    public void clearTableRow(){
        int count=jTable_sellproduct.getRowCount();
        for(int i=0;i<count;i++){
            model.removeRow(0);
        }
        jTextField_productid.setText("");
    }
        
    private void jButton_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_printActionPerformed
        // TODO add your handling code here:
        ArrayList<Sales> list=new ArrayList();
        int count=jTable_sellproduct.getRowCount();
        for(int i=0;i<count;i++)
        {
            int pid=Integer.parseInt(model.getValueAt(i,0).toString());
            int sid=TrackUser.uid;
            double price=Double.parseDouble(model.getValueAt(i, 2).toString());
            int qty=Integer.parseInt(model.getValueAt(i, 3).toString());
            Date d=new Date();
            //create model class sales object and set these values
            Sales ob= new Sales();
            ob.setPid(pid);
            ob.setSid(sid);
            ob.setPrice(price);
            ob.setQty(qty);
            ob.setDos(d);
            //add this object to list
            list.add(ob);
                  
    }//GEN-LAST:event_jButton_printActionPerformed
//hand over this list to controller salesDAO
        SalesDAO sDAO= new SalesDAO();
            sDAO.insertData(list);
            printBill();
            clearTableRow();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_print;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_grandtotal;
    private javax.swing.JLabel jLabel_grandtotal1;
    private javax.swing.JLabel jLabel_productid;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_sellproduct;
    private javax.swing.JTextField jTextField_productid;
    // End of variables declaration//GEN-END:variables
}

